# Generated by Django 2.1.3 on 2019-02-08 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuilderCallInfo',
            fields=[
                ('builder', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='management.Builder')),
                ('default_number', models.CharField(blank=True, choices=[('KooKoo', 'KooKoo')], max_length=20, null=True)),
                ('type_of_connection', models.CharField(blank=True, choices=[('KooKoo', 'KooKoo')], max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BuilderCallInfoKookoo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, db_column='name', max_length=100, null=True)),
                ('api_key', models.CharField(blank=True, db_column='api_key', max_length=100, null=True)),
                ('text_to_play', models.CharField(blank=True, db_column='text_to_play', max_length=100, null=True)),
                ('caller_id', models.CharField(blank=True, db_column='caller_id', max_length=100, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response_sid', models.CharField(blank=True, max_length=30, null=True)),
                ('requested_at', models.DateTimeField(db_index=True)),
                ('response_ms', models.PositiveIntegerField(default=0)),
                ('requested_params', models.TextField(blank=True, null=True)),
                ('requested_status_code', models.PositiveIntegerField(blank=True, null=True)),
                ('requested_method', models.CharField(max_length=10)),
                ('requested_response', models.TextField(blank=True, null=True)),
                ('requested_errors', models.TextField(blank=True, null=True)),
                ('requested_url', models.URLField()),
                ('user_remote_addr', models.GenericIPAddressField()),
                ('user_host', models.URLField()),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Request Log',
            },
        ),
        migrations.CreateModel(
            name='TelePhonekookoo',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('sid', models.CharField(max_length=255, unique=True)),
                ('call_type', models.CharField(blank=True, choices=[('In', 'Incomming'), ('Out', 'Outgoing')], max_length=20, null=True)),
                ('lead', models.IntegerField(blank=True, null=True)),
                ('status', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('phone', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.PhoneNumber')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='buildercallinfo',
            name='builder_call_info_kookoo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephone.BuilderCallInfoKookoo'),
        ),
    ]
