# Generated by Django 2.1.2 on 2019-02-28 07:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_auto_20190208_0805'),
        ('mail', '0002_email_mailid'),
    ]

    operations = [
        migrations.AddField(
            model_name='mail',
            name='mailid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='management.Emailaddress'),
        ),
    ]
