# Generated by Django 2.1.2 on 2019-02-28 07:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0003_mail_mailid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='email',
            old_name='mailid',
            new_name='mail_id',
        ),
    ]
