# Generated by Django 2.1.2 on 2019-02-28 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mail', '0004_auto_20190228_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='email',
            name='ext_attachments',
            field=models.ManyToManyField(blank=True, null=True, to='mail.ExternalAttachment'),
        ),
    ]
