# Generated by Django 2.1.3 on 2019-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FielsChanged',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feilds', models.CharField(blank=True, db_column='Source Date', max_length=30, null=True)),
                ('old_data', models.TextField(blank=True, db_column='Old Data', null=True)),
                ('new_data', models.TextField(blank=True, db_column='New Data', null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('NO', 'None'), ('system', 'system'), ('telephone_incomming', 'telephone_incomming'), ('telephone_outgoing', 'telephone_outgoing'), ('mail_outgoing', 'mail_outgoing'), ('cab', 'cab'), ('other', 'other')], db_column='Activity Type', default='NO', max_length=30)),
                ('is_sale', models.BooleanField(db_column='Is Sale', default=False)),
                ('next_enquiry_date', models.DateTimeField(blank=True, db_column='Next Enquiry Date', null=True)),
                ('remote_addr', models.GenericIPAddressField()),
                ('remote_url_requested', models.URLField()),
                ('comment', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
