# Generated by Django 2.1.3 on 2019-02-08 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mail', '0001_initial'),
        ('dashboard', '0001_initial'),
        ('management', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('telephone', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leadactivity',
            name='call_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.CallStatus'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='fiels_changed',
            field=models.ManyToManyField(blank=True, db_column='Fiels Changed', to='dashboard.FielsChanged'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='lead_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.LeadStatus'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='mail',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='mail.Email'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='sale_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='management.SaleStatus'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='telephone',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='telephone.TelePhonekookoo'),
        ),
        migrations.AddField(
            model_name='leadactivity',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
    ]
