# Generated by Django 2.1.3 on 2019-02-08 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AgentAvailability',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_date', models.DateTimeField()),
                ('to_date', models.DateTimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='APILead',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chVisitid', models.CharField(max_length=200)),
                ('compid', models.CharField(max_length=200)),
                ('visemail', models.CharField(blank=True, max_length=200, null=True)),
                ('visphone', models.CharField(blank=True, max_length=200, null=True)),
                ('leadDate', models.CharField(blank=True, max_length=200, null=True)),
                ('customerName', models.CharField(blank=True, max_length=200, null=True)),
                ('country', models.CharField(blank=True, max_length=200, null=True)),
                ('city', models.CharField(blank=True, max_length=200, null=True)),
                ('propid', models.CharField(max_length=200)),
                ('property', models.CharField(max_length=200)),
                ('cmpname', models.CharField(max_length=200)),
                ('fldrname', models.CharField(blank=True, max_length=200, null=True)),
                ('serverid', models.CharField(blank=True, max_length=200, null=True)),
                ('websiteurl', models.CharField(blank=True, max_length=200, null=True)),
                ('source', models.CharField(blank=True, max_length=200, null=True)),
                ('additional', models.CharField(blank=True, max_length=200, null=True)),
                ('flag', models.BooleanField(default=True)),
                ('status_error', models.TextField(blank=True, max_length=200, null=True)),
            ],
        ),
    ]
